<?php include 'views/templates/header_template.phtml'; ?>


<body>

  <div class="container-meds">

    <?php if (!empty($errorSearch) && $errorSearch == true){ ?>
    <div class="container">
      <div class="alert alert-danger text-center mt-4" role="alert">
          <strong>¡Error!</strong> DNI o CHIP no existe
      </div>
    </div>

    <?php } ?>

    <div class="search-options mt-4">
      <div class="main">

        <div class="accordion acc-searcher">
            <div class="accordion-section">
                <a class="accordion-section-title text-center" href="#accordion-4">Buscar paciente</a>
                <div id="accordion-4" class="accordion-section-content">

                    <!-- Search form -->
                    <div class="input-group mb-3">
                        <form class="form w-100" action="index.php?action=basicInfoFarm" method="post">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Buscar por DNI" aria-label="Search term" aria-describedby="basic-addon" name="dni">
                                <div class="input-group-append">
                                    <button class="btn btn-outline-success" type="submit">Buscar</button>
                                </div>
                            </div>
                        </form>

                    </div>

                    <!-- Search form -->
                    <div class="input-group mb-3" >
                        <form class="form-inline w-100" action="index.php?action=searchPet" method="post">
                            <input type="number" class="form-control" placeholder="Buscar por CHIP" aria-label="Search term" aria-describedby="basic-addon" name="chip">
                            <div class="input-group-append">
                                <button class="btn btn-outline-success" type="submit">Buscar</button>
                            </div>
                        </form>
                    </div>
                </div>
                <!--end .accordion-section-content-->
            </div>
        </div>

      </div>

    </div>

</body>

</html>
