<?php include 'views/templates/header_template.phtml'; ?>

<body>

    <?php if (!empty($emptyPrescription) && $emptyPrescription == true) { ?>
        <div class="container mt-4">
            <div class="alert alert-warning text-center" role="alert">
                No hay recetas para esta mascota
            </div>
        </div>
    <?php } else { ?>
        <table class="table table-bordered table-light mt-2 ml-2 table-hover">
            <thead class="mb-4">

                <tr>
                    <th scope="col">Nombre</th>
                    <th scope="col">Especie</th>
                    <th scope="col">Edad</th>
                    <th scope="col">Peso</th>
                    <th scope="col">sexo</th>
                    <th scope="col">Medicamento</th>
                    <th scope="col">Comentario</th>
                    <th scope="col">cantidad</th>
                    <th scope="col">chip</th>
                    <th scope="col">Dni propietario</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($data['pets'] as $pet) { ?>
                    <tr>
                        <td><?php echo $pet['nombre'] ?></td>
                        <td><?php echo $pet['especie'] ?></td>
                        <td><?php echo $pet['age'] ?></td>
                        <td><?php echo $pet['peso'] ?></td>
                        <td><?php echo $pet['sexo'] ?></td>
                        <td><?php echo $pet['nombre_medicamento'] ?></td>
                        <td><?php echo $pet['observacion'] ?></td>
                        <td><?php echo $pet['cantidad'] ?></td>
                        <td><?php echo $pet['chip'] ?></td>
                        <td><?php echo $pet['dni_propietario'] ?></td>
                        <?php if ($pet['cronico'] == "n") { ?>
                            <td><a href="index.php?action=recogido&prescription=<?php echo $pet['id_receta'] ?>&chip=<?php echo $pet['chip'] ?>">Marcar como recogido</a></td>
                        <?php } else { ?>
                            <td>Es crónico</td>
                        <?php } ?>
                    </tr>
                <?php } ?>

            </tbody>
        </table>

    <?php } ?>

</body>

</html>
