<?php include 'views/templates/header_template.phtml'; ?>

<script src='https://www.google.com/recaptcha/api.js'></script>

<script type="text/javascript">
$(document).ready(function(){
  // Add smooth scrolling to all links
  $("a").on('click', function(event) {

    // Make sure this.hash has a value before overriding default behavior
    if (this.hash !== "") {
      // Prevent default anchor click behavior
      event.preventDefault();

      // Store hash
      var hash = this.hash;

      // Using jQuery's animate() method to add smooth page scroll
      // The optional number (800) specifies the number of milliseconds it takes to scroll to the specified area
      $('html, body').animate({
        scrollTop: $(hash).offset().top
      }, 800, function(){

        // Add hash (#) to URL when done scrolling (default click behavior)
        window.location.hash = hash;
      });
    } // End if
  });
});
</script>

<body>

  <div class="primary-bg">

    <!-- navbar -->
    <nav class="navbar mainpage">
      <ul>
        <li><a href="#client" style="font-size: 16px">MyPetCard para clientes</a></li>
        <li><a href="#vet" style="font-size: 16px">Veterinarios</a></li>
        <li><a href="#farm" style="font-size: 16px">Farmacias</a></li>
        <li><a href="#lab" style="font-size: 16px">laboratorios</a></li>
      </ul>
    </nav>
    <!-- navbar -->

    <div class="login">

      <h2 class="login-header">Log in</h2>

      <form class="login-container" autocomplete="new-password" action="index.php?action=login" method="post">
        <p><input type="text" name="username" placeholder="username" autocomplete="new-password"></p>
        <p><input type="password" name="password" placeholder="Password" ></p>
      <!--<div class="g-recaptcha" data-sitekey="6LfoTFwUAAAAAHLU-wIipNaqppNqHQ0MquEuxF5a"></div> -->
      <div class="g-recaptcha ml-5" data-sitekey="6LfoTFwUAAAAAHLU-wIipNaqppNqHQ0MquEuxF5a"></div>

      <?php if (!empty($errorLogin) && $errorLogin == "yes") { ?>
        <div class="container mt-3">
          <div class="alert alert-danger">
          Usuario o contraseña incorrectos
          </div>
        </div>
      <?php } ?>
        <p><input type="submit" value="Log in"></p>
      </form>
    </div>

  </div>

  <div class="petCardUser text-center" id="client">

    <div class="container">
      <h1>¿Qué es My Pet Card?</h1>

      <div class="row">

        <div class="col-6 petCardUserCols" >
          <img src="imgs/petcard.png" class="mr-5" style="margin-top: 80px;width:80%">
        </div>

        <div class="petCardExplain text-justify col-6 petCardUserCols" style="font-size: 18px;">
          <p>My Pet Card es un sistema en el que todos los datos de su mascota se podrán visualizar vía web. El veterinario añadirá los medicamentos que necesite y la farmacia los podrá ver para no necesitar llevar consigo el papel de la receta.
            Así mismo podrá comprar medicamentos online que necesiten receta ya que se podrá comprobar si han sido recetados.
          </p>

          <br>

          <p>Ventajas</p>
          <ul>
            <li>Cómodo</li>
            <li>Fácil</li>
            <li>Ágil</li>
          </ul>

        </div>

      </div>

    </div>
  </div>

  <div class="petCardVet" id="vet">
    <div class="container text-justify">

      <div class="row">
        <div class="col-6" style="font-size: 18px;">

          <h2 >My Pet Card para Veterinarios</h2>

          <p>Disfrute de poder recetar eligiendo entre todos los médicamentos, puediendo elegir el mejor, pudiendo filtrar por categorias, efectos, vías de administración y por mascota para así poder recetar el mejor medicamento para las mascotas.</p>

          <p>Fácil, sencillo, así se describe al programa, tan solo busque a la mascota, consulte sus datos como medicamentos recetados, comentarios, peso, edad, etc.</p>

          <p>Busque por CHIP o por DNI del dueño, consulte los nuevos medicamentos que van saliendo y mantengase actualizado y recete lo mejor.</p>

        </div>
        <div class="col-6">
          <img src="imgs/1.png" alt="">
        </div>http://optimizilla.com/es/

      </div>
    </div>

  </div>

  <div class="petCardFarm" id="farm">
    <div class="container text-justify">

      <div class="row">

        <div class="col-6">
          <img src="imgs/farm-min.png" alt="">

        </div>

        <div class="col-6" style="font-size: 18px;">

          <h2>My pet Card para Farmacias</h2>

          <p class="mt-4">Consulte qué se le ha recetado a las mascotas, busque por DNI o por CHIP, podrá ver si es un medicamento crónico o no, etc.</p>
        </div>

      </div>

    </div>
  </div>

  <div class="petCardLab" id="lab">
    <div class="container text-justify">

      <div class="row">

        <div class="col-6" style="font-size: 18px;">
          <h2>My pet Card para Laboratorios</h2>

          <p>Lance al mercado nuevos medicamentos fácilmente, cualquier veterinario podrá consultar su medicamento. Haga consultas para estudios de mercado y compruebe qué medicamento se vende más mediante gráficas para analizar el mercado.</p>

        </div>

        <div class="col-6">
          <img src="imgs/lab-min.png" alt="">
        </div>

      </div>
    </div>
  </div>


</body>

<footer class="footer-distributed m-0">

  <div class="footer-left">

    <h2>MyPetCard</h2>

    <p class="footer-links">
      <a href="#client">Clientes</a>·
      <a href="#vet">Veterinarios</a>·
      <a href="#farm">Farmacias</a>·
      <a href="#lab">laboratorios</a>
    </p>

    <p class="footer-company-name">MyPetCard &copy; 2018</p>
  </div>

  <div class="footer-center">

    <div  style="margin-top: 47px;">
      <i class="fa fa-envelope"></i>
      <p><a href="mailto:support@company.com">toninocampagna13@gmail.com</a></p>
    </div>

  </div>

  <div class="footer-right">

    <p class="footer-company-about">
      <span>Sobre My Pet Card </span>
      My pet card está disponible para quien lo desee, enviar email para más información.
    </p>


  </div>

</footer>


</html>
