<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>MY PET CARD</title>
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
  <link rel="stylesheet" href="views/css.css">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
  <script src="https://code.highcharts.com/stock/highstock.js"></script>
  <script src="https://code.highcharts.com/stock/modules/exporting.js"></script>
  <script src="https://code.highcharts.com/stock/modules/export-data.js"></script>

  <script type="text/javascript">
    $(document).ready(function(){

      $(".drawGraph").click(function(){
          graphic($(this).attr('graph'));
      });

    var seriesOptions = [],
    seriesCounter = 0;

    function graphic(cat) {

      $.ajax({
        type: "POST",
        url: "controllers/graph_controller.php",
        data: ({
          word: cat.toString()
        }),
        success: function(response) {
          var medicines = $.parseJSON(response);

          var count = Object.keys(medicines).length;
          console.log(count);
      //  console.log(medicines);

         $.each(medicines, function (id, name) {

           $.getJSON('?action=graph&medId='+id,    function (data) {
              seriesOptions[id] = {
                name: name,
                data: data
              };

              // As we're loading the data asynchronously, we don't know what order it will arrive. So
              // we keep a counter and create the chart when all the data is loaded.
              seriesCounter += 1;
              if (seriesCounter === count) {
                createChart(seriesOptions);
              }
            });


          });
        }
      });
    }


    function createChart(seriesOptions) {
      console.log(seriesOptions);



      Highcharts.stockChart('container', {

          rangeSelector: {
              selected: 4
          },

          yAxis: {
              labels: {
                  formatter: function () {
                      return (this.value > 0 ? ' + ' : '') + this.value + '%';
                  }
              },
              plotLines: [{
                  value: 0,
                  width: 2,
                  color: 'silver'
              }]
          },

          plotOptions: {
              series: {
                  compare: 'percent',
                  showInNavigator: true
              }
          },

          tooltip: {
              pointFormat: '<span style="color:{series.color}">{series.name}</span>: <b>{point.y}</b> ({point.change}%)<br/>',
              valueDecimals: 2,
              split: true
          },

          series: seriesOptions
      });




    }

    });
  </script>

</head>





<nav class="navbar navbar-expand-lg navbar-dark  user-navbar">
  <a class="navbar-brand" href="index.php">MY PET CARD</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="?action=petAddView">Añadir mascotas</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="index.php?action=logout">logout</a>
      </li>
    </ul>

    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Buscar acciones med." aria-label="Search" id="efectSearch">
    </form>

    <form class="form-inline my-2 my-lg-0" action="index.php?action=searchMedicine" method="post">
      <input class="form-control mr-sm-2" type="search" placeholder="Buscar medicamento" aria-label="Search" id="autocomplete" name="medicineName">
    </form>
  </div>
</nav>

<div class="">
  <button type="button" class="drawGraph" name="button" graph="1" _onclick="graphic(1)">Antiinflamatorio</button>
</div>

<div class="">
  <button type="button" class="drawGraph" name="button" graph="2" _onclick="graphic(2)">Antiparasitario interno</button>
</div>

<div class="" onclick="graphic(3)">
  Antifúngicos
</div>

<div class="" onclick="graphic(4)">
  Antiparasitario
</div>

<div id="container" style="height: 400px; min-width: 310px">

</div>


</body>

</html>
