<?php include 'views/templates/header_template.phtml'; ?>


<script>
    $(document).ready(function () {
        $('table.highchart').highchartTable();
    });
</script>

<body>
  
<div class="container mt-4">
           <div class="row">
             <?php foreach ($data['categories'] as $category) { ?>

                   <div class="col-3">
                       <div class="dropdown">
                         <form action="?action=graph&catMedicine=<?php echo $category['id'] ?>" method="post">
                            <button type="submit" class="btn btn-block btn-primary "  aria-expanded="false">
                                <span><?php echo $category['nombre'] ?></span>
                             </button>
                          </form>
                        </div>
                   </div>

            <?php } ?>
           </div>
       </div>

<div class="container" >

<div class="highchart-container mt-4" ></div>

  <?php if (!empty($html)) {
    echo $html;
  } ?>


</div>

<script>
jQuery(document).ready(function () {

  $(".highchart").css("display", "none");

});
</script>

</body>

</html>
