<?php include 'views/templates/header_template.phtml'; ?>


<body>

  <nav class="navbar navbar-expand-lg navbar-dark  user-navbar">
    <a class="navbar-brand" href="index.php">MY PET CARD</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="#">logout</a>
        </li>
      </ul>

  <form class="form-inline my-2 my-lg-0">
    <input class="form-control mr-sm-2" type="search"  placeholder="Buscar acciones med." aria-label="Search" <?php if($pet_view == "yes"){ ?> disabled <?php } ?> >
  </form>



      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2"  type="search" placeholder="Buscar medicamento" aria-label="Search" <?php if($pet_view == "yes"){ ?> disabled <?php } ?>>
      </form>
    </div>
  </nav>

  <table class="table table-striped table-light mt-2 ml-2 ">
    <thead class="mb-4">
      <?php if (!empty($data['pets']['medicamento'])){ ?>
      <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Especie</th>
        <th scope="col">Edad</th>
        <th scope="col">Peso</th>
        <th scope="col">sexo</th>
        <th scope="col">Medicamento crónico</th>
        <th scope="col">Comentario</th>
        <th scope="col">chip</th>
        <th scope="col">Dni propietario</th>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    <?php } else { ?>
      <th scope="col">Nombre</th>
      <th scope="col">Especie</th>
      <th scope="col">Edad</th>
      <th scope="col">Peso</th>
      <th scope="col">sexo</th>
      <th scope="col">chip</th>
      <th scope="col">Dni propietario</th>
      <th scope="col"></th>
      <th scope="col"></th>
    <?php } ?>
    </thead>
    <tbody>
      <?php foreach ($data['pets'] as $pet){ ?>
      <tr>
        <td><?php echo $pet['nombre'] ?></td>
        <td><?php echo $pet['especie'] ?></td>
        <td><?php echo $pet['age'] ?></td>
        <td><?php echo $pet['peso'] ?></td>
        <td><?php echo $pet['sexo'] ?></td>
        <td><?php echo $pet['chip'] ?></td>
        <td><?php echo $pet['dni_propietario'] ?></td>
        <td><a href="index.php?action=edit&pet=<?php echo $pet['id']?>">Editar</a></td>
        <td><a href="index.php?action=prescribeView&pet=<?php echo $pet['chip']?>">Recetar</a></td>
      </tr>
    <?php } ?>

    </tbody>
  </table>

</body>

</html>
