<?php include 'views/templates/header_template.phtml'; ?>


<body>

  <table class="table table-bordered table-light mt-2 ml-2 table-hover">
    <thead class="mb-4">
      <?php if (array_key_exists('medicamento', $data['pets'][0])){ ?>
      <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Especie</th>
        <th scope="col">Edad</th>
        <th scope="col">Peso</th>
        <th scope="col">sexo</th>
        <th scope="col">Medicamento crónico</th>
        <th scope="col">Comentario</th>
        <th scope="col">chip</th>
        <th scope="col">Dni propietario</th>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    <?php } else { ?>
      <th scope="col">Nombre</th>
      <th scope="col">Especie</th>
      <th scope="col">Edad</th>
      <th scope="col">Peso</th>
      <th scope="col">sexo</th>
      <th scope="col">chip</th>
      <th scope="col">Dni propietario</th>
      <th scope="col"></th>
      <th scope="col"></th>
    <?php } ?>

    </thead>
    <tbody>
      <?php if (array_key_exists('medicamento', $data['pets'][0])){ ?>
        <?php foreach ($data['pets'] as $pet){ ?>
      <tr>
        <form action="index.php?action=edit_pet&pet_chip=<?php echo $pet['chip'] ?>" method="post">
          <th><input class="" type="text" name="name" value="<?php echo $pet['nombre'] ?>"></th>
          <td><?php echo $pet['especie'] ?></td>
          <td><?php echo $pet['age'] ?></td>
          <td><input class="" type="number" name="weight" value="<?php echo $pet['peso'] ?>"></td>
          <td><?php echo $pet['sexo'] ?></td>
          <td><?php echo $pet['nombre_medicamento'] ?></td>
          <td><?php echo $pet['observacion'] ?></td>
          <td><?php echo $pet['chip'] ?></td>
          <td><input class="" type="text" name="dni" value="<?php echo $pet['dni_propietario'] ?>"></td>
          <td><input type="submit" value="aceptar"></td>
          <td><a href="index.php?action=deletePrescription&prescription=<?php echo $pet['id_medicamento']?>&&chip=<?php echo $pet['chip']?>">Eliminar receta</a></td>
          <td><a href="index.php?action=deletePet&pet=<?php echo $pet['id']?>">Eliminar mascota</a></td>
        </form>
      </tr>
      <?php } ?>
    <?php } else { ?>
      <?php foreach ($data['pets'] as $pet){ ?>
        <form action="index.php?action=edit_pet&pet_chip=<?php echo $pet['chip'] ?>" method="post">
          <tr>
            <th><input class="" type="text" name="name" value="<?php echo $pet['nombre'] ?>"></th>
            <td><?php echo $pet['especie'] ?></td>
            <td><?php echo $pet['age'] ?></td>
            <td><input class="" type="number" name="weight" value="<?php echo $pet['peso'] ?>"></td>
            <td><?php echo $pet['sexo'] ?></td>
            <td><?php echo $pet['chip'] ?></td>
            <td><input class="" type="text" name="dni" value="<?php echo $pet['dni_propietario'] ?>"></td>
            <td><input type="submit" value="aceptar"></td>
            <td><a href="index.php?action=deletePet&pet=<?php echo $pet['id']?>">Eliminar mascota</a></td>
          </tr>
        </form>
        <?php } ?>
      <?php } ?>
    </tbody>
  </table>

</body>

</html>
