<?php include 'views/templates/header_template.phtml'; ?>


<body>

  <table class="table table-bordered table-light mt-2 ml-2 table-hover">
    <thead class="mb-4">
      <?php if (array_key_exists('medicamento', $data['pets'][0])){ ?>
      <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Especie</th>
        <th scope="col">Edad</th>
        <th scope="col">Peso</th>
        <th scope="col">sexo</th>
        <th scope="col">Medicamento crónico</th>
        <th scope="col">Comentario</th>
        <th scope="col">chip</th>
        <th scope="col">Dni propietario</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    <?php } else { ?>
      <th scope="col">Nombre</th>
      <th scope="col">Especie</th>
      <th scope="col">Edad</th>
      <th scope="col">Peso</th>
      <th scope="col">sexo</th>
      <th scope="col">Medicamento crónico</th>
      <th scope="col">chip</th>
      <th scope="col">Dni propietario</th>
      <th scope="col"></th>
      <th scope="col"></th>
    <?php } ?>
    </thead>
    <tbody>
      <?php if (array_key_exists('medicamento', $data['pets'][0])){ ?>
        <?php foreach ($data['pets'] as $pet){ ?>
      <tr>
        <td><?php echo $pet['nombre'] ?></td>
        <td><?php echo $pet['especie'] ?></td>
        <td><?php echo $pet['age'] ?></td>
        <td><?php echo $pet['peso'] ?></td>
        <td><?php echo $pet['sexo'] ?></td>
        <td><?php echo $pet['nombre_medicamento'] ?></td>
        <td><?php echo $pet['observacion'] ?></td>
        <td><?php echo $pet['chip'] ?></td>
        <td><?php echo $pet['dni_propietario'] ?></td>
        <td><a href="index.php?action=edit&pet=<?php echo $pet['chip']?>">Editar</a></td>
        <td><a href="index.php?action=toPrescribe&chip=<?php echo $pet['chip']?>">Recetar</a></td>

      </tr>
      <?php } ?>
    <?php } else { ?>
      <?php foreach ($data['pets'] as $pet){ ?>
      <tr>
        <td><?php echo $pet['nombre'] ?></td>
        <td><?php echo $pet['especie'] ?></td>
        <td><?php echo $pet['age'] ?></td>
        <td><?php echo $pet['peso'] ?></td>
        <td><?php echo $pet['sexo'] ?></td>
        <td>No tiene medicamentos crónicos recetados</td>
        <td><?php echo $pet['chip'] ?></td>
        <td><?php echo $pet['dni_propietario'] ?></td>
        <td><a href="index.php?action=edit&pet=<?php echo $pet['chip']?>">Editar</a></td>
        <td><a href="index.php?action=toPrescribe&chip=<?php echo $pet['chip']?>">Recetar</a></td>
      </tr>

      <?php } ?>
    <?php } ?>

    </tbody>
  </table>

</body>

</html>
