<?php include 'views/templates/header_template.phtml'; ?>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark  user-navbar">
      <a class="navbar-brand" href="index.php">MY PET CARD</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                  <a class="nav-link"  href="?action=petAddView">Añadir mascotas</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link"  href="?action=petModify">Editar mascotas</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="index.php?action=logout">logout</a>
              </li>
          </ul>

          <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="search" placeholder="Buscar acciones med." aria-label="Search" id="efectSearch">
          </form>

          <form class="form-inline my-2 my-lg-0" action="index.php?action=searchMedicine" method="post">
              <input class="form-control mr-sm-2" type="search" placeholder="Buscar medicamento" aria-label="Search" id="autocomplete" name="medicineName">
          </form>
      </div>
  </nav>



  <div class="row container-meds">

    <div class="search-options">
      <div class="main">

        <div class="accordion acc-searcher mt-4">
            <div class="accordion-section">
                <a class="accordion-section-title text-center" href="#accordion-4">Buscar paciete</a>
                <div id="accordion-4" class="accordion-section-content">

                    <!-- Search form -->
                    <div class="input-group mb-3">
                      <form class="form w-100" action="index.php?action=edit_pet" method="post">
                      <div class="input-group">
                        <input type="text" class="form-control" placeholder="Buscar por DNI" aria-label="Search term" aria-describedby="basic-addon" name="dni">
                        <div class="input-group-append">
                            <button class="btn btn-outline-success" type="submit">Buscar</button>
                        </div>
                      </div>
                      </form>

                    </div>

                    <!-- Search form -->
                    <div class="input-group mb-3" >
                      <form class="form-inline w-100" action="index.php?action=edit_pet" method="post">
                        <input type="text" class="form-control" placeholder="Buscar por CHIP" aria-label="Search term" aria-describedby="basic-addon" name="chip">
                        <div class="input-group-append">
                            <button class="btn btn-outline-success" type="submit">Buscar</button>
                        </div>
                      </form>
                    </div>
                </div>
                <!--end .accordion-section-content-->
            </div>
        </div>



      </div>

    </div>




</body>

</html>
