<?php include 'views/templates/header_template.phtml'; ?>


<body>

  <nav class="navbar navbar-expand-lg navbar-dark  user-navbar">
    <a class="navbar-brand" href="#">MY PET CARD</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="#">logout</a>
        </li>
      </ul>

      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Buscar acciones med." aria-label="Search">
      </form>

      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Buscar medicamento" aria-label="Search">
      </form>
    </div>
  </nav>

  <table class="table table-striped table-light mt-2 ml-2 ">
    <thead>
      <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Especie</th>
        <th scope="col">Raza</th>
        <th scope="col">Edad</th>
        <th scope="col">Peso</th>
        <th scope="col">sexo</th>
        <th scope="col">Medicamento crónico</th>
        <th scope="col">Comentario</th>
        <th scope="col">chip</th>
        <th scope="col">Dni propietario</th>
        <th scope="col">Editar</th>



      </tr>
    </thead>
    <tbody>
        <?php foreach ($data['pets'] as $pet){ ?>
      <tr>
        <th><?php $pet['nombre'] ?></th>
        <td><?php $pet['especie_animal'] ?></td>
        <td><?php $pet['edad'] ?></td>
        <td><?php $pet['peso'] ?></td>
        <td><?php $pet['sexo'] ?></td>
        <td><?php $pet['med_cronico'] ?></td>
        <td><?php $pet['comentario'] ?></td>
        <td><?php $pet['chip'] ?></td>
        <td><?php $pet['dni_propietario'] ?></td>
        <td>Editar</td>
      </tr>
      <?php } ?>
      <tr>
        <th>Lili</th>
        <td>Canina</td>
        <td>Pastor Alemán</td>
        <td>5 Años</td>
        <td>20kg</td>
        <td>Fluimocil</td>
        <td>es hipertenso</td>
        <td>Editar</td>
      </tr>
      <tr>
        <th>Lili</th>
        <td>Canina</td>
        <td>Pastor Alemán</td>
        <td>5 Años</td>
        <td>20kg</td>
        <td>Fluimocil</td>
        <td>es hipertenso</td>
        <td>Editar</td>
      </tr>
    </tbody>
  </table>

</body>

</html>
