<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>My Pet Card</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script type="text/javascript" src="accordion.js"></script>
  <link rel="stylesheet" href="css.css">


</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark  user-navbar">
    <a class="navbar-brand" href="#">MY PET CARD</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="#">logout</a>
        </li>
      </ul>

      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Buscar acciones med." aria-label="Search">
      </form>

      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Buscar medicamento" aria-label="Search">
      </form>
    </div>
  </nav>

  <table class="table table-striped table-light mt-2 ml-2 ">
    <thead>
      <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Especie</th>
        <th scope="col">Raza</th>
        <th scope="col">Edad</th>
        <th scope="col">Peso</th>
        <th scope="col">Medicamento crónico</th>
        <th scope="col">Comentario</th>
        <th scope="col">Editar</th>



      </tr>
    </thead>
    <tbody>
      <tr>
        <th>Lili</th>
        <td>Canina</td>
        <td>Pastor Alemán</td>
        <td>5 Años</td>
        <td>20kg</td>
        <td>Fluimocil</td>
        <td>es hipertenso</td>
        <td>Editar</td>
      </tr>
      <tr>
        <th>Lili</th>
        <td>Canina</td>
        <td>Pastor Alemán</td>
        <td>5 Años</td>
        <td>20kg</td>
        <td>Fluimocil</td>
        <td>es hipertenso</td>
        <td>Editar</td>
      </tr>
      <tr>
        <th>Lili</th>
        <td>Canina</td>
        <td>Pastor Alemán</td>
        <td>5 Años</td>
        <td>20kg</td>
        <td>Fluimocil</td>
        <td>es hipertenso</td>
        <td>Editar</td>
      </tr>
    </tbody>
  </table>

</body>

</html>
