<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>MY PET CARD</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script type="text/javascript" src="views/accordion.js"></script>
  <link rel="stylesheet" href="views/css.css">
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark  user-navbar">
    <a class="navbar-brand" href="#">MY PET CARD</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="views/vet_add_pet_view.html">Añadir mascotas</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="views/vet_add_med_view.html">Añadir medicametos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">logout</a>
        </li>
      </ul>

      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Buscar acciones med." aria-label="Search">
      </form>

      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Buscar medicamento" aria-label="Search">
      </form>
    </div>
  </nav>



  <div class="row container-meds">

    <div class="left-options">
      <div class="main">

        <div class="accordion acc-searcher">
              <div class="accordion-section">
                <a class="accordion-section-title text-center" href="#accordion-4">Buscar paciete</a>
                <div id="accordion-4" class="accordion-section-content">

                  <!-- Search form -->
                  <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="Buscar por DNI" aria-label="Search term" aria-describedby="basic-addon">
                    <div class="input-group-append">
                      <button class="btn btn-outline-success" type="button">Buscar</button>
                    </div>
                  </div>

                  <!-- Search form -->
                  <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="Buscar por CHIP" aria-label="Search term" aria-describedby="basic-addon">
                    <div class="input-group-append">
                      <button class="btn btn-outline-success" type="button">Buscar</button>
                    </div>
                  </div>
                </div>
                <!--end .accordion-section-content-->
              </div>
            </div>

        <div class="accordion">
          <div class="accordion-section">
            <a class="accordion-section-title text-left" href="#accordion-1">Especie</a>
            <div id="accordion-1" class="accordion-section-content">
              <div class="funkyradio">
                <div class="funkyradio-default">
                  <input type="checkbox" name="checkbox" id="checkbox1" checked/>
                  <label for="checkbox1">First Option default</label>
                </div>
                <div class="funkyradio-primary">
                  <input type="checkbox" name="checkbox" id="checkbox2" checked/>
                  <label for="checkbox2">Second Option primary</label>
                </div>
                <div class="funkyradio-success">
                  <input type="checkbox" name="checkbox" id="checkbox3" checked/>
                  <label for="checkbox3">Third Option success</label>
                </div>
                <div class="funkyradio-danger">
                  <input type="checkbox" name="checkbox" id="checkbox4" checked/>
                  <label for="checkbox4">Fourth Option danger</label>
                </div>
                <div class="funkyradio-warning">
                  <input type="checkbox" name="checkbox" id="checkbox5" checked/>
                  <label for="checkbox5">Fifth Option warning</label>
                </div>
                <div class="funkyradio-info">
                  <input type="checkbox" name="checkbox" id="checkbox6" checked/>
                  <label for="checkbox6">Sixth Option info</label>
                </div>
              </div>
            </div>
            <!--end .accordion-section-content-->
          </div>
          <!--end .accordion-section-->

          <div class="accordion-section">
            <a class="accordion-section-title text-left" href="#accordion-2">Categorias</a>
            <div id="accordion-2" class="accordion-section-content">
              <p>Mauris interdum fringilla augue vitae tincidunt. Curabitur vitae tortor id eros euismod ultrices. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent nulla mi, rutrum ut feugiat at, vestibulum ut
                neque? Cras tincidunt enim vel aliquet facilisis. Duis congue ullamcorper vehicula. Proin nunc lacus, semper sit amet elit sit amet, aliquet pulvinar erat. Nunc pretium quis sapien eu rhoncus. Suspendisse ornare gravida mi, et placerat
                tellus tempor vitae.</p>
            </div>
            <!--end .accordion-section-content-->
          </div>
          <!--end .accordion-section-->

          <div class="accordion-section">
            <a class="accordion-section-title text-left" href="#accordion-3">Vía de administración</a>
            <div id="accordion-3" class="accordion-section-content">
              <p>Mauris interdum fringilla augue vitae tincidunt. Curabitur vitae tortor id eros euismod ultrices. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent nulla mi, rutrum ut feugiat at, vestibulum ut
                neque? Cras tincidunt enim vel aliquet facilisis. Duis congue ullamcorper vehicula. Proin nunc lacus, semper sit amet elit sit amet, aliquet pulvinar erat. Nunc pretium quis sapien eu rhoncus. Suspendisse ornare gravida mi, et placerat
                tellus tempor vitae.</p>
            </div>
            <!--end .accordion-section-content-->
          </div>
          <!--end .accordion-section-->
        </div>
        <!--end .accordion-->


      </div>

    </div>

    <div class="col-3">
      <div class="card">
        <img class="card-img-top" src="http://success-at-work.com/wp-content/uploads/2015/04/free-stock-photos.gif">
        <div class="card-block">
          <h4 class="card-title">Nombre medicamento</h4>
          <div class="meta">
            <a href="#">Categoria</a>
          </div>
          <div class="card-text">
            contra qué actua - contra qué actua - contra qué actua - contra qué actua - contra qué actua - contra qué actua -
          </div>
        </div>
        <div class="card-footer">
          <button name="id" value="" class="btn btn-outline-success float-right btn-sm">Recetar</button>
        </div>
      </div>
    </div>



</body>

</html>
