<?php include 'views/templates/header_template.phtml'; ?>

<nav class="navbar navbar-expand-lg navbar-dark  user-navbar">
    <a class="navbar-brand" href="index.php">MY PET CARD</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link"  href="?action=petAddView">Añadir mascotas</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="index.php?action=logout">logout</a>
            </li>
        </ul>

        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Buscar acciones med." aria-label="Search" id="efectSearch">
        </form>

        <form class="form-inline my-2 my-lg-0" action="index.php?action=searchMedicine" method="post">
            <input class="form-control mr-sm-2" type="search" placeholder="Buscar medicamento" aria-label="Search" id="autocomplete" name="medicineName">
        </form>
    </div>
</nav>



<div class="mt-4 container-meds mr-0 ml-2 row">



    <div class=" col-3">
        <div class="main">

          <form class="mb-4" action="?action=generarRecetas" method="post">
            <button type="submit" name="button">Generar recetas aleatorias</button>
          </form>

            <div class="accordion acc-searcher">
                <div class="accordion-section">
                    <a class="accordion-section-title text-center" href="#accordion-4">Buscar paciete</a>
                    <div id="accordion-4" class="accordion-section-content">

                        <!-- Search form -->
                        <div class="input-group mb-3">
                          <form class="form w-100" action="index.php?action=searchPet" method="post">
                          <div class="input-group">
                            <input type="text" class="form-control" placeholder="Buscar por DNI" aria-label="Search term" aria-describedby="basic-addon" name="dni">
                            <div class="input-group-append">
                                <button class="btn btn-outline-success" type="submit">Buscar</button>
                            </div>
                          </div>
                          </form>

                        </div>

                        <!-- Search form -->
                        <div class="input-group mb-3" >
                          <form class="form-inline w-100" action="index.php?action=searchPet" method="post">
                            <input type="text" class="form-control" placeholder="Buscar por CHIP" aria-label="Search term" aria-describedby="basic-addon" name="chip">
                            <div class="input-group-append">
                                <button class="btn btn-outline-success" type="submit">Buscar</button>
                            </div>
                          </form>
                        </div>
                    </div>
                    <!--end .accordion-section-content-->
                </div>
            </div>

            <div class="accordion">

                <div class="accordion-section">
                    <a class="accordion-section-title text-left" href="#accordion-1">Especie</a>
                    <div id="accordion-1" class="accordion-section-content">
                        <div class="funkyradio">
                            <?php foreach ($data['species'] as $spec) { ?>

                                <div class="funkyradio-danger">

                                    <input type="checkbox" class="filterProduct" name="checkbox" id="checkboxPet<?php echo $spec['id']; ?>" />
                                    <label for="checkboxPet<?php echo $spec['id']; ?>"><?php echo $spec['especie']; ?></label>

                                </div>
                            <?php } ?>
                        </div>
                    </div>
                    <!--end .accordion-section-content-->
                </div>
                <!--end .accordion-section-->

                <div class="accordion-section">
                    <a class="accordion-section-title text-left" href="#accordion-2">Categorias</a>
                    <div id="accordion-2" class="accordion-section-content">
                        <div class="funkyradio">
                            <?php foreach ($data['categories'] as $category) { ?>

                                <div class="funkyradio-danger">

                                    <input type="checkbox" class="filterProduct" name="checkbox" id="checkboxCateg<?php echo $category['id']; ?>" />
                                    <label for="checkboxCateg<?php echo $category['id']; ?>"><?php echo $category['nombre']; ?></label>

                                </div>
                            <?php } ?>
                        </div>
                    </div>
                    <!--end .accordion-section-content-->
                </div>
                <!--end .accordion-section-->

                <div class="accordion-section">
                    <a class="accordion-section-title text-left" href="#accordion-3">Vía de administración</a>
                    <div id="accordion-3" class="accordion-section-content">
                        <div class="funkyradio">
                            <?php foreach ($data['administration'] as $administration) { ?>

                                <div class="funkyradio-danger">

                                    <input type="checkbox" name="checkbox" id="checkboxAdm<?php echo $administration['id']; ?>" />
                                    <label for="checkboxAdm<?php echo $administration['id']; ?>"><?php echo $administration['administramiento']; ?></label>

                                </div>
                            <?php } ?>
                        </div>
                    </div>
                    <!--end .accordion-section-content-->
                </div>
                <!--end .accordion-section-->
            </div>
            <!--end .accordion-->


        </div>

    </div>



    <div class="col-9 row medicine-container" style="padding-right: 0px;">

      <?php if ($presError == "true") { ?>
          <div class="alert alert-danger ml-5  mt-4 text-center col-9 alert-presc" role="alert">
              Error el recetar
          </div>
      <?php } elseif ($presError == "false") { ?>
        <div class="alert alert-success mt-4 text-center col-9 alert-presc ml-5" role="alert">
            Se ha añadido la receta correctamente
        </div>

      <?php } ?>

        <?php foreach ($data['medicines'] as $medicine) { ?>

            <div class="card mb-5 mx-5 col-xl-3 col-lg-4 col-md-4  card-medicines">
                <img class="card-img-top" src="<?php echo $medicine['url'] ?>" style="width:70%">
                <div class="card-block">
                    <h4 class="card-title"><?php echo $medicine['nombre'] ?></h4>
                    <div class="meta">
                        <span data-toggle="modal" href="#modal" class="categoria" id="checkboxCateg<?php echo $medicine['id_cat']; ?>"><?php echo $medicine['categoria'] ?></span>
                    </div>
                    <div class="meta">
                        <span data-toggle="modal" href="#modal" class="administramiento" id="checkboxAdm<?php echo $medicine['id_adm']; ?>"><?php echo $medicine['administramiento'] ?></span>
                    </div>
                    <div class="card-text">
                        <?php echo $medicine['efecto'] ?>
                    </div>
                    <form action="index.php?action=addPresciption&id=<?php echo $medicine['id'] ?>" method="post">
                    <div class="collapse mt-2" id="collapseExample<?php echo $medicine['id'] ?>">
                        <div class="card card-body">
                            <div class="meta">
                                <span class="mt-2">Efecto Secundario</span>
                            </div>
                            <?php echo $medicine['efecto_secundario'] ?>
                        </div>
                        <div class="row mt-4">
                            <div class="col-6">
                                <div class="form-group">
                                    <input type="number" class="form-control"  placeholder="Cantidad" name="quantity">
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-check mt-2">
                                    <input type="checkbox" class="form-check-input" value="y" name="chronic">
                                    <label class="form-check-label" for="exampleCheck1">Medicamento crónico</label>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="comment">Observación</label>
                            <textarea class="form-control" rows="5" id="comment" name="observation"></textarea>
                        </div>

                        <div class="form-group">
                            <label for="usr">Número de chip:</label>
                            <input type="text" class="form-control" name="chip">
                        </div>
                        <button name="id" type="submit" class="btn btn-outline-danger float-right btn-sm" data-toggle="collapse" data-target="#collapseExample">Confirmar receta</button>

                    </div>
                  </form>


                </div>
                <div class="card-footer">
                    <button name="id" value="" class="btn btn-outline-success float-right btn-sm" data-toggle="collapse" data-target="#collapseExample<?php echo $medicine['id'] ?>">Recetar</button>
                </div>
                <?php if (!empty($medicine['especie'])) { ?>
                    <div class = "meta mt-3 text-center mb-3">

                        <?php foreach ($medicine['especie'] as $especie) {

                            if($especie['especie'] == "perro"){ ?>
                                <span><img src="imgs/animals/perro.png" alt=""></span>
                            <?php } elseif ($especie['especie'] == "gato") { ?>
                                <span><img src="imgs/animals/cat.png" alt=""></span>
                          <?php  } elseif ($especie['especie'] == "conejo") { ?>
                                <span><img src="imgs/animals/rabbit.png" alt=""></span>
                          <?php } elseif ($especie['especie'] == "hurón") { ?>
                                <span><img src="imgs/animals/ferret.png" alt=""></span>
                          <?php } ?>
                        <?php } ?>
                    </div>
                <?php } ?>

            </div>


        <?php } ?>


    </div>
</body>

</html>
