<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>MY PET CARD</title>
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script type="text/javascript" src="views/accordion.js"></script>
  <link rel="stylesheet" href="views/css.css">
  <script type="text/javascript" src="views/jquery.autocomplete.min.js"></script>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
  <script src="views/jquery.min.js" type="text/javascript"></script>
  <script src="views/highcharts.js" type="text/javascript"></script>
  <script src="views/jquery.highchartTable.js" type="text/javascript"></script>
</head>

<?php if(!empty($_SESSION['userType'])){ ?>

<nav class="navbar navbar-expand-lg navbar-dark  user-navbar">
    <a class="navbar-brand" href="index.php">MY PET CARD</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav nav">
          <?php if($_SESSION['userType'] == "veterinario"){ ?>
            <li class="nav-item">
                <a class="nav-link"  href="?action=petAddView">Añadir mascotas</a>
            </li>
            <li class="nav-item">
                <a class="nav-link"  href="?action=petModify">Editar mascotas</a>
            </li>
          <?php } ?>
            <li class="nav-item ">
                <a class="nav-link" href="index.php?action=logout">logout</a>
            </li>
        </ul>

        <?php if($_SESSION['userType'] == "veterinario"){ ?>
        <div class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Buscar acciones med." aria-label="Search" id="efectSearch">
        </div>

        <form class="form-inline my-2 my-lg-0" action="index.php?action=searchMedicine" method="post">
            <input class="form-control mr-sm-2" type="search" placeholder="Buscar medicamento" aria-label="Search" id="autocomplete" name="medicineName">
        </form>
        <?php } ?>
    </div>
</nav>

<?php } ?>
