<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <title>MY PET CARD</title>
        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" async="async">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" ></script>
        <script type="text/javascript" src="views/js/js-min.js" ></script>
        <link rel="stylesheet" href="views/css/css-min.css" async="async">
        <script type="text/javascript" src="views/js/jquery.autocomplete.min.js" ></script>
        <link rel="stylesheet" async="async" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">

    </head>

    <?php if (!empty($_SESSION['userType'])) { ?>

        <nav class="navbar navbar-expand-lg navbar-dark  user-navbar">
            <a class="navbar-brand" href="index.php">MY PET CARD</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav nav mr-auto">
                    <?php if ($_SESSION['userType'] == "veterinario") { ?>
                        <li class="nav-item">
                            <a class="nav-link"  href="?action=petAddView">Añadir mascotas</a>
                        </li>
                    <?php } ?>
                    <li class="nav-item ">
                        <a class="nav-link" href="index.php?action=logout">logout</a>
                    </li>
                </ul>

                <?php if ($_SESSION['userType'] == "veterinario") { ?>
                    <div class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="search" placeholder="Buscar acciones med." aria-label="Search" id="efectSearch" <?php if (!empty($pet_view) && $pet_view == "yes") { ?> disabled <?php } ?>>
                    </div>

                    <form class="form-inline my-2 my-lg-0" action="index.php?action=searchMedicine" method="post">
                        <input class="form-control mr-sm-2" type="search" placeholder="Buscar medicamento" aria-label="Search" id="autocomplete" name="medicineName" <?php if (!empty($pet_view) && $pet_view == "yes") { ?> disabled <?php } ?>>
                    </form>
                <?php } ?>
            </div>
        </nav>

    <?php } ?>
